---
- hosts: local

  gather_facts: false
  
  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
    
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
    
    
  tasks: 
    - name: Create an instance
      ec2:
        instance_type: t2.micro
        image: ami-ee6f5e8b
        wait: yes
        group: web-access-testing
        count: 1
        key_name: Ansible_AWS_tmp
        region: us-east-2
        instance_tags: 
          Name: Mootube Instance
      register: ec2
      
    - debug: var=ec2