---
- hosts: vb
  
  tasks:
    - ping: ~
    
    - name: Upgrade API Package Manager repositories cache
      become: true
      apt:
        update_cache: yes
        
    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe
        
    - name: Install cowsay ~ it's probably important 
      apt:
        name: cowsay
      become: true 
      
    - name: Install Git VCS
      become: true
      apt:
        name: git
        state: latest
  